import SwiftUI

/// C1: shown once, before the mic ever opens and before any network call. It names each
/// third-party AI provider, as App Review Guideline 5.1.2(i) requires.
struct ConsentView: View {
    @Environment(AppState.self) private var state
    @State private var showDetails = false

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(alignment: .leading, spacing: 8) {
                    Text("To answer you, your voice and questions are sent to our server and to **OpenAI** and **Anthropic**.")
                        .font(.system(size: 15.5))
                    Text("Never used for training. Deleted after 30 days.")
                        .font(Theme.small)
                        .foregroundStyle(Theme.dim)
                    HStack(spacing: 8) {
                        Button("Details") { showDetails = true }
                            .buttonStyle(.pill(.secondary))
                        Button("Agree") { state.agreeToConsent() }
                            .buttonStyle(.pill(.primary))
                    }
                    .padding(.top, 4)
                }
                .frame(maxWidth: .infinity, alignment: .leading)
            }
            .navigationTitle("Welcome")
            .containerBackground(Color.black, for: .navigation)
            .sheet(isPresented: $showDetails) { ConsentDetailsView() }
        }
    }
}

private struct ConsentDetailsView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 10) {
                // Keep this in sync with the gateway's provider config (server/src/config.ts).
                // Default gateway config calls Anthropic directly. If LLM_PROVIDER=openrouter, name OpenRouter here too.
                // Legal should confirm the final wording.
                detail("Your voice", "Sent to OpenAI to turn speech into text, and in Live mode to hold the conversation.")
                detail("Your questions", "Sent to Anthropic (Claude) to write the answer.")
                detail("Spoken answers", "Generated by OpenAI's text-to-speech.")
                detail("Retention", "Our providers don't train on your data. We delete conversations after 30 days.")
                detail("No account", "We create an anonymous ID for this watch. There's no sign-up.")
                Link("Privacy policy", destination: AppConfig.privacyURL)
                    .font(Theme.small)
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
        .navigationTitle("Details")
    }

    private func detail(_ title: String, _ body: String) -> some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(title).font(.system(size: 14, weight: .semibold)).foregroundStyle(Theme.amber)
            Text(body).font(Theme.small)
        }
    }
}
